CREATE TABLE IF NOT EXISTS \"employees\" (
	\"id\" serial,
	\"name\" text,
	\"address\" text,
	\"phone\" text,
	\"email\" text,
	\"pay_type\" text,
	\"birthdate\" text,
	\"marital_status\" text,
	\"job_title\" text,
	\"department\" text,
	\"supervisor\" text,
	\"work_location\" text,
	\"work_email\" text,
	\"work_number\" text,
	\"start_date\" text,
	\"emergency_name\" text,
	\"emergency_address\" text,
	\"emergency_phone\" text,
	\"emergency_relationship\" text,
	\"pay_rate\" text,
	\"pay_yearly\" text,
	PRIMARY KEY( id )
);